---
name: Test

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.github/dependabot.yml'

env:
  IMAGE: ghcr.io/redlinetriad/molecule-vagrant-qemu-action

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Build Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Molecule on Runner
        run: |
          python3 -m pip install molecule molecule-vagrant

      - name: Create molecule scenario
        run: |
          mkdir test
          cd test
          molecule init role --driver-name vagrant test.validate
          cp ../test_files/molecule.yml validate/molecule/default/molecule.yml
          sed -i 's/test.//g' validate/molecule/default/converge.yml

      - name: Test Molecule default pipeline
        uses: ./ # Uses an action in the root directory
        with:
          molecule_working_dir: test/validate
          image: "${{ env.IMAGE }}:test"
